### ISSUE TITLE
Potentially risky use of copy-properties

### ISSUE THREAD

**Issue by jona-as** [adamwaite/AJWValidator#11]
In AJWValidator there are two properties of type NSMutableArray, which are declared as copy. If one would use these properties to set the respective arrays it would cause a problem which most likely will result in a crash:

```objective-c
self.mutableErrorMessages = [NSMutableArray array];

[self.rules addObject:@"test"]; 
/*Preceding line results in: Terminating app due to uncaught exception 'NSInvalidArgumentException',  reason: '-[__NSArrayI addObject:]: unrecognized selector sent to instance*/
```

Due to the usage of copy, the setter would copy the given NSMutableArray into an IMMUTABLE NSArray instance hence causing every call of NSMutableArray specific methods to throw an NSInvalidArgumentException.

**Comment by adamwaite** [comment]
Well spotted. Sorted in https://github.com/adamwaite/AJWValidator/commit/ca670a5f359317b7f6d2242f9daa9ef6b89e5401.
