### ISSUE TITLE
podsepc public_header_files exclude "ALPValidatorRule.h"?

### ISSUE THREAD

**Issue by pcicp** [adamwaite/AJWValidator#9]
dear adamwaite, why public_header_files exclude "ALPValidatorRule.h"? 

i want to use rule then inherit and override something. in my xcode project (using Pods), i can't import ALPValidatorRule.h

could you update podsepc?

**Comment by adamwaite** [comment]
I had hidden the rule file because I couldn't think of a reason to expose it, why do want to override something?  

I plan to refactor the library to use protocols over an abstract rule object eventually anyway.

**Comment by adamwaite** [comment]
(closed by accident, reopened now)

**Comment by picp** [comment]
e, i want to add new rule like email, url (this is a suck that using a block for these generic validation every time) . also i need a name/tag/identifer to lookup specified rule in validator rules, auto created same type message, resort validation order, or control other details.

**Comment by adamwaite** [comment]
I'll take a look at this today. I'm unsure what your last sentence is trying to say I'm afraid. If you need all this additional functionality why don't you fork the library?
